# image: mobiledevops/flutter-sdk-image:latest

# variables:

# cache:
#   key: analyze_and_test_acbs
#   paths:
#     - .pub-cache/global_packages

stages:
  - analyze_and_test

# before_script:
#   - export PATH="$PATH":"$HOME/.flutter-sdk/.pub-cache/bin"
#   - flutter pub get
#   # - flutter pub global activate junitreport
#   - flutter upgrade
#   - dart pub outdated
#   - dart pub upgrade

flutter_test:
  stage: analyze_and_test
  script:
    - flutter format --set-exit-if-changed .
    - flutter analyze
  artifacts:
    when: always
    # reports:
    #   junit:
    #     - report.xml
  tags:
    - cts_ci
  # only:
  #   - merge_requests
