name: flutter_mobile
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  charts_flutter: ^0.12.0
  collection: ^1.15.0
  connectivity_plus: ^2.1.0
  cookie_jar: ^3.0.1
  cupertino_icons: ^1.0.2
  device_info: ^2.0.2
  dio: ^4.0.0
  dio_cookie_manager: ^2.0.0
  firebase_analytics: ^9.0.5
  firebase_core: ^1.11.0
  firebase_crashlytics: ^2.4.5
  firebase_database: ^9.0.5
  firebase_messaging: ^11.2.5
  firebase_remote_config: ^1.0.4
  fl_chart: ^0.41.0
  flutter:
    sdk: flutter
  flutter_cached_pdfview: ^0.4.1
  flutter_local_notifications: ^8.2.0
  flutter_localizations:
    sdk: flutter
  flutter_slidable: ^0.6.0
  flutter_svg: ^1.0.0
  fluttertoast: ^8.0.8
  get: ^4.3.0
  get_cli: ^1.6.0
  get_storage: ^2.0.3
  grouped_list: ^5.1.2
  grpc: ^3.0.2
  horizontal_data_table: 3.6.1+1
  implicitly_animated_reorderable_list: ^0.4.2
  intl: ^0.17.0
  keyboard_dismisser: ^2.0.0
  local_auth: ^1.1.11
  logging: ^1.0.2
  lottie: ^1.4.0
  otp: ^3.0.2
  package_info_plus: ^1.4.0
  pattern_formatter: 2.0.0
  pull_to_refresh: ^2.0.0
  rxdart: ^0.27.1
  socket_io_client: ^1.0.1
  syncfusion_flutter_charts: ^19.4.53
  treemap: ^0.4.0
  url_launcher: ^6.0.12
  uuid: ^3.0.4
  web_socket_channel: ^2.2.0
  webview_flutter: ^3.0.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Roboto-Bold
      fonts:
        - asset: fonts/roboto/Roboto-Bold.ttf
    - family: Roboto-Italic
      fonts:
        - asset: fonts/roboto/Roboto-Italic.ttf
    - family: Roboto-Medium
      fonts:
        - asset: fonts/roboto/Roboto-Medium.ttf
    - family: Roboto-Regular
      fonts:
        - asset: fonts/roboto/Roboto-Regular.ttf

  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/
